
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

fib1 = 1
fib2 = 2
finish = 4000000
sum = 0

while fib2 < finish:
    if fib2 % 2 == 0:
        sum += fib2
    aux = fib1 + fib2
    fib1 = fib2
    fib2 = aux

print('The sum of all even Fibonacci number up to four million is equal to', sum)

